language: java
sudo: false
addons:
  sonarcloud:
    organization: "tango-controls" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
script:
  - chmod 777 ./jmvcc
  - ./jmvcc jmvc/assemble
  - test -e build/distributions/TangoWebapp.war
after_success:
  - sonar-scanner -Dsonar.projectKey=org.tango-controls:TangoWebapp -Dsonar.sources=. -Dsonar.exclusions=build/**,jmvc/**,docs/**,apps/**
deploy:
  - provider: releases
    prerelease: true
    api_key: $GITHUB_OAUTH_TOKEN
    file: "build/distributions/TangoWebapp.war"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
